name: Release
on:
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  build:
    name: "publish to npm"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: npm i
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
