name: Lint and Unit Tests
on: [pull_request, push]

jobs:
  unit-test:
    name: "test: lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: asdf_install
        uses: asdf-vm/actions/install@v1
        with:
          before_install: bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
      - run: npm install
      - run: npm test
