name: Lint and Unit Tests
on: [pull_request, push]

jobs:
  unit-test:
    name: "test: lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: asdf_install
        uses: asdf-vm/actions/install@v1
      - run: npm install
      - run: npm test
